name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14.x
  FORCE_COLOR: 1

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn install
      - run: yarn lint

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn install
      - run: yarn test:ember
